#!/bin/bash

# Verifies that the checked-in golden file for the Foxglove schema codegen tool matches what the
# tool currently produces. This primarily serves to make changes to the generator's output visible
# in code review. The checked-in golden file can be regenerated by running:
#
#   bazel run @aos//tools/foxglove/schema_descriptions:copy_generated_file

set -euo pipefail
diff -u "$1" "$2"
