use std::{
    ffi::CString,
    os::raw::{c_char, c_void},
    path::Path,
    ptr,
};

use thiserror::Error;

use aos_configuration_fbs::aos::{Channel as RustChannel, Configuration as RustConfiguration};
use aos_flatbuffers::{transmute_table_to, NonSizePrefixedFlatbuffer};

#[repr(C)]
pub struct Configuration {
    _unused: [u8; 0],
}

#[repr(C)]
pub struct Channel {
    _unused: [u8; 0],
}

#[repr(C)]
pub struct Node {
    _unused: [u8; 0],
}

#[repr(C)]
struct aos_configuration_buffer_t {
    _unused: [u8; 0],
}

extern "C" {
    fn aos_configuration_get_channel(
        config: *const Configuration,
        name_data: *const c_char,
        name_size: usize,
        type_data: *const c_char,
        type_size: usize,
        application_name_data: *const c_char,
        application_name_size: usize,
        node: *const Node,
    ) -> *const Channel;

    fn aos_configuration_get_node(
        config: *const Configuration,
        name_data: *const c_char,
        name_size: usize,
    ) -> *const Node;

    fn aos_configuration_channel_has_type(channel: *const Channel) -> bool;
    fn aos_configuration_channel_type(channel: *const Channel) -> *const c_char;
    fn aos_configuration_channel_has_name(channel: *const Channel) -> bool;
    fn aos_configuration_channel_name(channel: *const Channel) -> *const c_char;

    fn aos_configuration_buffer_get_data(
        buffer: *const aos_configuration_buffer_t,
    ) -> *const c_void;
    fn aos_configuration_buffer_get_size(buffer: *const aos_configuration_buffer_t) -> usize;
    fn aos_configuration_buffer_maybe_read_from_file(
        file_path: *const c_char,
        extra_import_paths: *const *const c_char,
        extra_import_paths_count: usize,
    ) -> *mut aos_configuration_buffer_t;
    fn aos_configuration_buffer_destroy(buffer: *mut aos_configuration_buffer_t);
}

#[derive(Clone, Copy, Eq, PartialEq, Debug, Error)]
pub enum ChannelLookupError {
    #[error("channel not found")]
    NotFound,
}

#[derive(Clone, Copy, Eq, PartialEq, Debug, Error)]
pub enum NodeLookupError {
    #[error("node not found")]
    NotFound,
}

#[derive(Clone, Copy, Eq, PartialEq, Debug, Error)]
pub enum ReadConfigError {
    #[error("duplicate imports or invalid paths")]
    ReadFailed,
}

impl<'a> Into<&'a Configuration> for RustConfiguration<'a> {
    fn into(self) -> &'a Configuration {
        unsafe { transmute_table_to(&self._tab) }
    }
}

/// A trait with useful helper methods for a `Configuration` table. Import this trait to get these
/// methods on both the `Configuration` struct generated by autocxx from the C++ code generated by
/// flatbuffers, and the `Configuration` struct generated by flatbuffers in Rust.
pub trait ConfigurationExt<'a>: Into<&'a Configuration> {
    fn get_channel(
        self,
        name: &str,
        typename: &str,
        application_name: &str,
        node: Option<&Node>,
    ) -> Result<&'a Channel, ChannelLookupError> {
        // SAFETY: All the input references are valid pointers, and we're not doing anything with
        // the result yet. It doesn't store any of the input references.
        let channel = unsafe {
            aos_configuration_get_channel(
                self.into(),
                name.as_ptr() as *const c_char,
                name.len(),
                typename.as_ptr() as *const c_char,
                typename.len(),
                application_name.as_ptr() as *const c_char,
                application_name.len(),
                node.map_or(ptr::null(), |p| p),
            )
        };
        if channel.is_null() {
            Err(ChannelLookupError::NotFound)
        } else {
            // SAFETY: We know this is a valid pointer now, and we're returning it with the lifetime
            // inherited from `self` which owns it.
            Ok(unsafe { &*channel })
        }
    }

    fn get_node(self, name: &str) -> Result<&'a Node, NodeLookupError> {
        // SAFETY: All the input references are valid pointers, and we're not doing anything with
        // the result yet. It doesn't store any of the input references.
        let node = unsafe {
            aos_configuration_get_node(self.into(), name.as_ptr() as *const c_char, name.len())
        };
        if node.is_null() {
            Err(NodeLookupError::NotFound)
        } else {
            // SAFETY: We know this is a valid pointer now, and we're returning it with the lifetime
            // inherited from `self` which owns it.
            Ok(unsafe { &*node })
        }
    }
}

impl<'a, T: Into<&'a Configuration>> ConfigurationExt<'a> for T {}

impl<'a> Into<&'a Channel> for RustChannel<'a> {
    fn into(self) -> &'a Channel {
        unsafe { transmute_table_to(&self._tab) }
    }
}

pub trait ChannelExt<'a>: Into<&'a Channel> {
    fn type_(self) -> Option<&'a str> {
        let c = self.into();
        unsafe {
            if aos_configuration_channel_has_type(c) {
                let ptr = aos_configuration_channel_type(c);
                let c_str = std::ffi::CStr::from_ptr(ptr);
                Some(c_str.to_str().expect("Channel type is invalid UTF-8"))
            } else {
                None
            }
        }
    }

    fn name(self) -> Option<&'a str> {
        let c = self.into();
        unsafe {
            if aos_configuration_channel_has_name(c) {
                let ptr = aos_configuration_channel_name(c);
                let c_str = std::ffi::CStr::from_ptr(ptr);
                Some(c_str.to_str().expect("Channel name is invalid UTF-8"))
            } else {
                None
            }
        }
    }
}

impl<'a, T: Into<&'a Channel>> ChannelExt<'a> for T {}

/// # Panics
///
/// `path` must be valid UTF-8.
pub fn read_config_from(
    path: &Path,
) -> Result<NonSizePrefixedFlatbuffer<RustConfiguration<'static>, Vec<u8>>, ReadConfigError> {
    read_config_from_import_paths(path, &[])
}

/// # Panics
///
/// `path` and all members of `extra_import_paths` must be valid UTF-8.
pub fn read_config_from_import_paths(
    path: &Path,
    extra_import_paths: &[&Path],
) -> Result<NonSizePrefixedFlatbuffer<RustConfiguration<'static>, Vec<u8>>, ReadConfigError> {
    let path_str = CString::new(path.to_str().expect("Paths must be UTF-8")).unwrap();
    let extra_import_paths_c: Vec<CString> = extra_import_paths
        .iter()
        .map(|p| CString::new(p.to_str().expect("Paths must be UTF-8")).unwrap())
        .collect();
    let extra_import_paths_ptrs: Vec<*const c_char> =
        extra_import_paths_c.iter().map(|c| c.as_ptr()).collect();

    unsafe {
        let buffer = aos_configuration_buffer_maybe_read_from_file(
            path_str.as_ptr(),
            extra_import_paths_ptrs.as_ptr(),
            extra_import_paths_ptrs.len(),
        );
        if buffer.is_null() {
            return Err(ReadConfigError::ReadFailed);
        }
        let data_ptr = aos_configuration_buffer_get_data(buffer);
        let size = aos_configuration_buffer_get_size(buffer);
        let slice = std::slice::from_raw_parts(data_ptr as *const u8, size);
        let buffer_vec = slice.to_vec();
        aos_configuration_buffer_destroy(buffer);
        // SAFETY: The C++ code returns a valid flatbuffer (unless it returned an error, which we
        // checked above).
        Ok(NonSizePrefixedFlatbuffer::new_unchecked(buffer_vec))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use aos_flatbuffers::Flatbuffer;
    use aos_testing_path::artifact_path;

    #[test]
    fn read_config() {
        let config =
            read_config_from(&artifact_path(Path::new("aos/testdata/config1.json"))).unwrap();
        assert!(
            config
                .message()
                .channels()
                .unwrap()
                .iter()
                .find(|channel| channel.type_() == Some(".aos.bar"))
                .is_some(),
            "Failed to find the .aos.bar channel: {:?}",
            config.message()
        );
    }
}
