use std::{ffi::CString, os::raw::c_char, path::Path, ptr};

use thiserror::Error;

use aos_configuration_fbs::aos::{Channel as RustChannel, Configuration as RustConfiguration};
pub use aos_events_event_loop_c::{
    aos_channel_t as Channel, aos_configuration_t as Configuration, aos_node_t as Node,
};
use aos_events_event_loop_c::{
    aos_configuration_buffer_destroy, aos_configuration_buffer_get_data,
    aos_configuration_buffer_get_size, aos_configuration_buffer_maybe_read_from_file,
    aos_configuration_channel_has_name, aos_configuration_channel_has_type,
    aos_configuration_channel_name, aos_configuration_channel_type, aos_configuration_get_channel,
    aos_configuration_get_node,
};
use aos_flatbuffers::{transmute_table_to, NonSizePrefixedFlatbuffer};

#[derive(Clone, Copy, Eq, PartialEq, Debug, Error)]
pub enum ChannelLookupError {
    #[error("channel not found")]
    NotFound,
}

#[derive(Clone, Copy, Eq, PartialEq, Debug, Error)]
pub enum NodeLookupError {
    #[error("node not found")]
    NotFound,
}

#[derive(Clone, Copy, Eq, PartialEq, Debug, Error)]
pub enum ReadConfigError {
    #[error("duplicate imports or invalid paths")]
    ReadFailed,
}

/// Reinterprets a table as the pointer the C API wants.
///
/// This is a local trait rather than [`Into`] because `Configuration` is now a type from the
/// generated bindings, so `impl Into<&Configuration> for RustConfiguration` would be an
/// implementation of a foreign trait over foreign types.
pub trait AsConfiguration<'a>: Sized {
    fn as_configuration(self) -> &'a Configuration;
}

impl<'a> AsConfiguration<'a> for RustConfiguration<'a> {
    fn as_configuration(self) -> &'a Configuration {
        // SAFETY: Both sides are a pointer to the same flatbuffers table.
        unsafe { transmute_table_to(&self._tab) }
    }
}

impl<'a> AsConfiguration<'a> for &'a Configuration {
    fn as_configuration(self) -> &'a Configuration {
        self
    }
}

/// A trait with useful helper methods for a `Configuration` table. Import this trait to get these
/// methods on both the opaque `Configuration` the C API hands out and the `Configuration` struct
/// generated by flatbuffers in Rust.
pub trait ConfigurationExt<'a>: AsConfiguration<'a> {
    fn get_channel(
        self,
        name: &str,
        typename: &str,
        application_name: &str,
        node: Option<&Node>,
    ) -> Result<&'a Channel, ChannelLookupError> {
        // SAFETY: All the input references are valid pointers, and we're not doing anything with
        // the result yet. It doesn't store any of the input references.
        let channel = unsafe {
            aos_configuration_get_channel(
                self.as_configuration(),
                name.as_ptr() as *const c_char,
                name.len(),
                typename.as_ptr() as *const c_char,
                typename.len(),
                application_name.as_ptr() as *const c_char,
                application_name.len(),
                node.map_or(ptr::null(), |p| p),
            )
        };
        if channel.is_null() {
            Err(ChannelLookupError::NotFound)
        } else {
            // SAFETY: We know this is a valid pointer now, and we're returning it with the lifetime
            // inherited from `self` which owns it.
            Ok(unsafe { &*channel })
        }
    }

    fn get_node(self, name: &str) -> Result<&'a Node, NodeLookupError> {
        // SAFETY: All the input references are valid pointers, and we're not doing anything with
        // the result yet. It doesn't store any of the input references.
        let node = unsafe {
            aos_configuration_get_node(
                self.as_configuration(),
                name.as_ptr() as *const c_char,
                name.len(),
            )
        };
        if node.is_null() {
            Err(NodeLookupError::NotFound)
        } else {
            // SAFETY: We know this is a valid pointer now, and we're returning it with the lifetime
            // inherited from `self` which owns it.
            Ok(unsafe { &*node })
        }
    }
}

impl<'a, T: AsConfiguration<'a>> ConfigurationExt<'a> for T {}

/// The [`AsConfiguration`] equivalent for channels.
pub trait AsChannel<'a>: Sized {
    fn as_channel(self) -> &'a Channel;
}

impl<'a> AsChannel<'a> for RustChannel<'a> {
    fn as_channel(self) -> &'a Channel {
        // SAFETY: Both sides are a pointer to the same flatbuffers table.
        unsafe { transmute_table_to(&self._tab) }
    }
}

impl<'a> AsChannel<'a> for &'a Channel {
    fn as_channel(self) -> &'a Channel {
        self
    }
}

pub trait ChannelExt<'a>: AsChannel<'a> {
    fn type_(self) -> Option<&'a str> {
        let c = self.as_channel();
        unsafe {
            if aos_configuration_channel_has_type(c) {
                let ptr = aos_configuration_channel_type(c);
                let c_str = std::ffi::CStr::from_ptr(ptr);
                Some(c_str.to_str().expect("Channel type is invalid UTF-8"))
            } else {
                None
            }
        }
    }

    fn name(self) -> Option<&'a str> {
        let c = self.as_channel();
        unsafe {
            if aos_configuration_channel_has_name(c) {
                let ptr = aos_configuration_channel_name(c);
                let c_str = std::ffi::CStr::from_ptr(ptr);
                Some(c_str.to_str().expect("Channel name is invalid UTF-8"))
            } else {
                None
            }
        }
    }
}

impl<'a, T: AsChannel<'a>> ChannelExt<'a> for T {}

/// # Panics
///
/// `path` must be valid UTF-8.
pub fn read_config_from(
    path: &Path,
) -> Result<NonSizePrefixedFlatbuffer<RustConfiguration<'static>, Vec<u8>>, ReadConfigError> {
    read_config_from_import_paths(path, &[])
}

/// # Panics
///
/// `path` and all members of `extra_import_paths` must be valid UTF-8.
pub fn read_config_from_import_paths(
    path: &Path,
    extra_import_paths: &[&Path],
) -> Result<NonSizePrefixedFlatbuffer<RustConfiguration<'static>, Vec<u8>>, ReadConfigError> {
    let path_str = CString::new(path.to_str().expect("Paths must be UTF-8")).unwrap();
    let extra_import_paths_c: Vec<CString> = extra_import_paths
        .iter()
        .map(|p| CString::new(p.to_str().expect("Paths must be UTF-8")).unwrap())
        .collect();
    let extra_import_paths_ptrs: Vec<*const c_char> =
        extra_import_paths_c.iter().map(|c| c.as_ptr()).collect();

    unsafe {
        let buffer = aos_configuration_buffer_maybe_read_from_file(
            path_str.as_ptr(),
            extra_import_paths_ptrs.as_ptr(),
            extra_import_paths_ptrs.len(),
        );
        if buffer.is_null() {
            return Err(ReadConfigError::ReadFailed);
        }
        let data_ptr = aos_configuration_buffer_get_data(buffer);
        let size = aos_configuration_buffer_get_size(buffer);
        let slice = std::slice::from_raw_parts(data_ptr as *const u8, size);
        let buffer_vec = slice.to_vec();
        aos_configuration_buffer_destroy(buffer);
        Ok(NonSizePrefixedFlatbuffer::new_unchecked(buffer_vec))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use aos_flatbuffers::Flatbuffer;
    use aos_testing_path::artifact_path;

    #[test]
    fn read_config() {
        let config =
            read_config_from(&artifact_path(Path::new("aos/testdata/config1.json"))).unwrap();
        assert!(
            config
                .message()
                .channels()
                .unwrap()
                .iter()
                .find(|channel| channel.type_() == Some(".aos.bar"))
                .is_some(),
            "Failed to find the .aos.bar channel: {:?}",
            config.message()
        );
    }
}
