load("@aos//aos/flatbuffers:flatbuffers_python.bzl", "flatbuffer_py_library")
load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("//aos/flatbuffers:build_defs.bzl", "flatbuffer_rust_library")
load("//aos/flatbuffers:generate.bzl", "static_flatbuffer")
load("//aos/flatbuffers:typescript.bzl", "flatbuffer_ts_library")

copy_file(
    name = "reflection_fbs_copy",
    src = "@com_github_google_flatbuffers//reflection:reflection_fbs_schema",
    out = "reflection.fbs",
)

# This autogenerates both a reflection_static.h and a reflection_generated.h.
# However, in order to avoid having two conflicting headers floating around,
# we forcibly override the #include to use flatbuffers/reflection_generated.h
# in static_flatbuffers.cc
static_flatbuffer(
    name = "reflection_fbs",
    srcs = ["reflection.fbs"],
    visibility = ["//visibility:public"],
)

flatbuffer_ts_library(
    name = "reflection_ts_fbs",
    srcs = ["reflection.fbs"],
    include_reflection = False,
    ts_files = ["reflection/%s" % (name,) for name in [
        "advanced-features.ts",
        "base-type.ts",
        "enum.ts",
        "enum-val.ts",
        "field.ts",
        "key-value.ts",
        "object.ts",
        "rpccall.ts",
        "schema-file.ts",
        "schema.ts",
        "service.ts",
        "type.ts",
    ]] + ["reflection.ts"],
    visibility = ["//visibility:public"],
)

npm_package(
    name = "flatbuffers_reflection",
    srcs = [":reflection_ts_fbs_ts"],
    include_external_repositories = ["*"],
    package = "flatbuffers_reflection",
    visibility = ["//visibility:public"],
)

flatbuffer_rust_library(
    name = "reflection_rust_fbs",
    srcs = ["reflection.fbs"],
    crate_name = "flatbuffers_reflection",
    include_reflection = False,
    visibility = ["//visibility:public"],
)

flatbuffer_py_library(
    name = "reflection_fbs_py",
    src = "reflection.fbs",
    visibility = ["//visibility:public"],
)
