def _runfile_path(ctx, file):
    path = file.short_path
    if path.startswith("../"):
        return path[3:]
    return ctx.workspace_name + "/" + path

def _sanitizer_wrapper_impl(ctx):
    cc_toolchain = ctx.attr._cc_toolchain[cc_common.CcToolchainInfo]

    # Configure features to check which sanitizer features are active
    feature_configuration = cc_common.configure_features(
        ctx = ctx,
        cc_toolchain = cc_toolchain,
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )

    # Check enabled features
    ubsan_enabled = cc_common.is_enabled(
        feature_name = "ubsan",
        feature_configuration = feature_configuration,
    )
    asan_enabled = cc_common.is_enabled(
        feature_name = "asan",
        feature_configuration = feature_configuration,
    )
    msan_enabled = cc_common.is_enabled(
        feature_name = "msan",
        feature_configuration = feature_configuration,
    )
    tsan_enabled = cc_common.is_enabled(
        feature_name = "tsan",
        feature_configuration = feature_configuration,
    )

    any_sanitizer_enabled = ubsan_enabled or asan_enabled or msan_enabled or tsan_enabled

    symbolizer_file = None
    sanitizer_library_file = None

    if any_sanitizer_enabled:
        # 1. Find llvm-symbolizer in toolchain files
        for f in cc_toolchain.all_files.to_list():
            if f.path.endswith("bin/llvm-symbolizer") or f.basename == "llvm-symbolizer":
                symbolizer_file = f
                break

        # 2. Locate the corresponding sanitizer library if needed
        if ubsan_enabled:
            for f in cc_toolchain.all_files.to_list():
                if f.basename == "libclang_rt.ubsan_standalone.so":
                    sanitizer_library_file = f
                    break
        elif asan_enabled:
            for f in cc_toolchain.all_files.to_list():
                if f.basename == "libclang_rt.asan.so":
                    sanitizer_library_file = f
                    break

    # 3. Generate script content
    symbolizer_path = ""
    if symbolizer_file:
        symbolizer_path = _runfile_path(ctx, symbolizer_file)

    sanitizer_lib_path = ""
    if sanitizer_library_file:
        sanitizer_lib_path = _runfile_path(ctx, sanitizer_library_file)

    # Extract the unset_preload file (which is required for wrapping Python targets)
    unset_preload_file = ctx.file._unset_preload
    unset_preload_path = _runfile_path(ctx, unset_preload_file)

    # Format wrapper script
    script_content = """#!/bin/bash
# Generated by sanitizer_wrapper.bzl. DO NOT EDIT.

if [ -n "$TEST_SRCDIR" ]; then
  RUNFILES_DIR="$TEST_SRCDIR"
else
  RUNFILES_DIR="${0}.runfiles"
fi
"""

    if symbolizer_path:
        script_content += """
export ASAN_SYMBOLIZER_PATH="$RUNFILES_DIR/{symbolizer_path}"
export MSAN_SYMBOLIZER_PATH="$ASAN_SYMBOLIZER_PATH"
""".format(symbolizer_path = symbolizer_path)

        ubsan_opts = "external_symbolizer_path=$ASAN_SYMBOLIZER_PATH"
        if ctx.attr.ubsan_options:
            ubsan_opts += ":" + ctx.attr.ubsan_options
        script_content += 'export UBSAN_OPTIONS="{}"\n'.format(ubsan_opts)

        tsan_opts = "external_symbolizer_path=$ASAN_SYMBOLIZER_PATH"
        if ctx.attr.tsan_options:
            tsan_opts += ":" + ctx.attr.tsan_options
        script_content += 'export TSAN_OPTIONS="{}"\n'.format(tsan_opts)

    if sanitizer_lib_path:
        script_content += """
# If the target executable is a Python bootstrap/wrapper script, we must preload the sanitizer library.
# We also preload `unset_preload.so` so that once the python process starts, it unsets LD_PRELOAD
# to prevent it from propagating to child subprocesses.
is_py_wrapper=0
if [ -f "$1" ]; then
  if grep -q "STAGE2_BOOTSTRAP" "$1" 2>/dev/null; then
    is_py_wrapper=1
  fi
fi

if [ "$is_py_wrapper" -eq 1 ]; then
  unset_path="$RUNFILES_DIR/{unset_preload_path}"
  lib_path="$RUNFILES_DIR/{sanitizer_lib_path}"
  export LD_PRELOAD="${{LD_PRELOAD:+${{LD_PRELOAD}}:}}$lib_path:$unset_path"
""".format(unset_preload_path = unset_preload_path, sanitizer_lib_path = sanitizer_lib_path)

        # Disable leak detection when preloading ASan into the uninstrumented python interpreter,
        # otherwise ASan/LSan will report leaks in the interpreter itself.
        if asan_enabled:
            asan_opts_list = ["detect_leaks=0"]
            if ctx.attr.asan_options:
                asan_opts_list.append(ctx.attr.asan_options)
            asan_opts = ":".join(asan_opts_list)
            script_content += '  export ASAN_OPTIONS="${{ASAN_OPTIONS:+${{ASAN_OPTIONS}}:}}{}"\n'.format(asan_opts)

        script_content += "fi\n"

    script_content += """
exec "$@"
"""

    # 4. Write script to output file
    output_script = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.write(
        output = output_script,
        content = script_content,
        is_executable = True,
    )

    # 5. Collect runfiles (symbolizer, sanitizer library, and unset_preload)
    runfiles_list = [unset_preload_file]
    if symbolizer_file:
        runfiles_list.append(symbolizer_file)
    if sanitizer_library_file:
        runfiles_list.append(sanitizer_library_file)

    return [
        DefaultInfo(
            executable = output_script,
            runfiles = ctx.runfiles(files = runfiles_list),
        ),
    ]

sanitizer_wrapper = rule(
    implementation = _sanitizer_wrapper_impl,
    executable = True,
    fragments = ["cpp"],
    attrs = {
        "asan_options": attr.string(default = ""),
        "tsan_options": attr.string(default = ""),
        "ubsan_options": attr.string(default = ""),
        "_cc_toolchain": attr.label(
            default = Label("@bazel_tools//tools/cpp:current_cc_toolchain"),
        ),
        "_unset_preload": attr.label(
            default = Label("//tools:unset_preload"),
            allow_single_file = True,
            cfg = "target",
        ),
    },
    toolchains = ["@bazel_tools//tools/cpp:toolchain_type"],
)
